apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
    - name: cluster
      port: 6222
    - name: management
      port: 8222
