apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: filebeat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
