apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  mysql-custom.cnf: |
    [client]
    default-character-set=utf8mb4
    [mysqld]
    innodb_buffer_pool_size=800M
    max_connections=500
    gtid_mode=ON
    enforce-gtid-consistency=ON
  master.cnf: |
    [mysqld]
    log-bin
  slave.cnf: |
    [mysqld]
    read-only
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cm9vdA=="
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:8
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              echo [mysqld] > /etc/mysql/conf.d/server-id.cnf
              echo server-id=$((1 + $ordinal)) >> /etc/mysql/conf.d/server-id.cnf
              cp /mnt/config/mysql-custom.cnf /etc/mysql/conf.d
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/config/master.cnf /etc/mysql/conf.d
              else
                cp /mnt/config/slave.cnf /etc/mysql/conf.d
              fi
          volumeMounts:
            - name: mysql-config
              mountPath: /mnt/config
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql
        - name: dump-data
          image: mysql:8
          envFrom:
            - secretRef:
                name: mysql
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              if [[ $ordinal -eq 0 ]]; then
                echo do nothing
              else
                until mysql -hmysql-0.mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; do sleep 5; done
                rm -f /data/mysql-snapshot/master-database.sql
                mysql -hmysql-0.mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "FLUSH TABLES WITH READ LOCK"
                mysqldump --all-databases --master-data -hmysql-0.mysql -uroot -p${MYSQL_ROOT_PASSWORD} > /data/mysql-snapshot/master-database.sql
              fi
          volumeMounts:
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql
            - name: mysql-snapshot
              mountPath: /data/mysql-snapshot
      containers:
        - name: mysql
          image: mysql:8
          envFrom:
            - secretRef:
                name: mysql
          volumeMounts:
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql
            - name: mysql-snapshot
              mountPath: /data/mysql-snapshot
        - name: start-slave
          image: mysql:8
          envFrom:
            - secretRef:
                name: mysql
          command:
            - bash
            - "-c"
            - |
              set -ex
              echo hello
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              until mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; do sleep 5; done
              if [[ $ordinal -eq 0 ]]; then
                mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER 'repl'@'%' IDENTIFIED BY 'repl';"
                mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';"
                mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "FLUSH PRIVILEGES;"
              else
                mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} < /data/mysql-snapshot/master-database.sql
                mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "CHANGE MASTER TO MASTER_HOST = 'mysql-0.mysql', MASTER_PORT = 3306, MASTER_USER = 'repl', MASTER_PASSWORD = 'repl', MASTER_AUTO_POSITION = 1, GET_MASTER_PUBLIC_KEY = 1;"
                mysql -h127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} -e "start slave;"
                mysql -hmysql-0.mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "UNLOCK TABLES"
              fi
              while true
              do
                sleep 5
                echo hello
              done

          volumeMounts:
            - name: conf
              mountPath: /etc/mysql/conf.d
            - name: mysql
              mountPath: /var/lib/mysql
            - name: mysql-snapshot
              mountPath: /data/mysql-snapshot

      restartPolicy: Always
      volumes:
        - name: conf
          emptyDir: {}
        - name: mysql-config
          configMap:
            name: mysql
        - name: mysql
          emptyDir: {}
        - name: mysql-snapshot
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None
