apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
  labels:
    app: mitmproxy
spec:
  selector:
    matchLabels:
      app: mitmproxy
  template:
    metadata:
      name: mitmproxy
      labels:
        app: mitmproxy
    spec:
      containers:
        - name: mitmproxy
          image: mitmproxy/mitmproxy
          imagePullPolicy: IfNotPresent
          command: ["mitmweb", "--listen-host", "0.0.0.0", "--web-host", "0.0.0.0"]
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
      