apiVersion: v1
kind: ConfigMap
metadata:
  name: superset
data:
  SUPERSET_SECRET_KEY: "JgUaBs9jcR9kzX8Cgf4t"
  TALISMAN_ENABLED: "False"
  superset_config.py: |
    LANGUAGES = {
        "en": {"flag": "us", "name": "English"},
        "zh": {"flag": "cn", "name": "Chinese"},
    }
    SQLALCHEMY_DATABASE_URI = (
      f"""sqlite:///{os.path.join(DATA_DIR, "superset.db")}?check_same_thread=false"""
    )
    # SQLALCHEMY_DATABASE_URI = 'mysql://root:root@mysql/data'
