apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      name: superset
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset:4.0.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: superset
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /app/superset_config.py
              name: superset-config
              subPath: superset_config.py
      restartPolicy: Always
      volumes:
        - name: superset-config
          configMap:
            name: superset
