apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      name: superset
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset:4.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: SUPERSET_HOME
              value: /data/superset
          envFrom:
            - configMapRef:
                name: superset
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/superset_config.py
              name: superset-config
              subPath: superset_config.py
            - mountPath: /data/superset
              name: superset
      restartPolicy: Always
      volumes:
        - name: superset-config
          configMap:
            name: superset
        - name: superset
          persistentVolumeClaim:
            claimName: superset
